"""Effect lines per spell. Everything else (range, components, duration, and so on) is read from
the spell file. Format: slug -> (lines, material_gp, consumed)."""

B = {
 "alarm": ([("util_alarm",1),("area_cube20",1),("lim_no_combat",1)],0,False),
 "animal-friendship": ([("cond_charmed",1),("lim_type",1),("lim_end_on_harm",1)],0,False),
 "bane": ([("die_bonus",1),("target_extra",2),("lim_save_negates",1)],0,False),
 "bless": ([("die_bonus",1),("target_extra",2),("lim_willing",1)],0,False),
 "burning-hands": ([("dmg",10.5),("rel_save_half",1),("area_cone15",1),("util_ignite",1)],0,False),
 "charm-person": ([("cond_charmed",1),("lim_type",1),("lim_aware",1),("lim_save_adv",1)],0,False),
 "color-spray": ([("cond_blinded",1),("area_cone15",1),("no_save",1),("lim_hp_pool",1)],0,False),
 "command": ([("cond_command",1),("lim_exclude",1),("lim_harmless_only",1)],0,False),
 "comprehend-languages": ([("util_language",1),("lim_no_combat",1)],0,False),
 "create-or-destroy-water": ([("util_create_water",1),("area_cube20",1),("lim_no_combat",1)],0,False),
 "cure-wounds": ([("heal",7.5),("lim_exclude",1)],0,False),
 "detect-evil-and-good": ([("util_detect",1),("area_radius30",1),("lim_barrier",1)],0,False),
 "detect-magic": ([("util_detect",1),("util_detect_aura",1),("area_radius30",1),("lim_barrier",1)],0,False),
 "detect-poison-and-disease": ([("util_detect",1),("area_radius30",1),("lim_barrier",1)],0,False),
 "disguise-self": ([("util_disguise",1),("lim_physical_reveal",1)],0,False),
 "divine-favor": ([("dmg_rider",2.5)],0,False),
 "entangle": ([("cond_restrained",1),("area_square20",1),("difficult_terrain",1),("lim_escape_check",1)],0,False),
 "expeditious-retreat": ([("extra_dash",1)],0,False),
 "faerie-fire": ([("advantage_vs_target",1),("util_outline",1),("area_cube20",1)],0,False),
 "false-life": ([("temp_hp",6.5)],0,False),
 "feather-fall": ([("fall_immunity",1),("target_extra",4),("lim_trigger",1)],0,False),
 "find-familiar": ([("util_familiar",1),("persist",1)],10,True),
 "fog-cloud": ([("heavy_obscure",1),("area_radius20",1)],0,False),
 "goodberry": ([("heal",5),("util_food",1),("lim_decay",1),("lim_slow_heal",1)],0,False),
 "grease": ([("cond_prone",1),("area_square10",1),("difficult_terrain",1)],0,False),
 "guiding-bolt": ([("dmg",14),("rel_attack",1),("advantage_next",1)],0,False),
 "healing-word": ([("heal",5.5),("lim_exclude",1)],0,False),
 "hellish-rebuke": ([("dmg",11),("rel_save_half",1),("lim_trigger",1)],0,False),
 "heroism": ([("temp_hp_recurring",3),("immune_frightened",1),("lim_willing",1)],0,False),
 "hideous-laughter": ([("cond_prone",1),("cond_incapacitated",1),("lim_repeat_save",1),("lim_exclude",1),("lim_save_adv",1)],0,False),
 "hunters-mark": ([("dmg_rider",3.5),("util_mark_track",1),("util_mark_move",1)],0,False),
 "identify": ([("util_lore",2),("lim_no_combat",1)],100,False),
 "illusory-script": ([("util_script",1),("lim_no_combat",1)],10,False),
 "inflict-wounds": ([("dmg",16.5),("rel_attack",1)],0,False),
 "jump": ([("jump_triple",1)],0,False),
 "longstrider": ([("speed_bonus",10)],0,False),
 "mage-armor": ([("ac_bonus",3),("lim_armor",1),("lim_willing",1)],0,False),
 "magic-missile": ([("dmg",10.5),("rel_auto",1),("split_targets",1)],0,False),
 "protection-from-evil-and-good": ([("protect_types",1),("lim_willing",1)],0,False),
 "purify-food-and-drink": ([("util_purify",1),("lim_no_combat",1)],0,False),
 "sanctuary": ([("util_ward",1),("lim_ends_on_attack",1)],0,False),
 "shield": ([("ac_bonus",5),("magic_missile_immune",1),("lim_trigger",1)],0,False),
 "shield-of-faith": ([("ac_bonus",2)],0,False),
 "silent-image": ([("util_illusion_image",1),("area_cube15",1),("lim_physical_reveal",1),("lim_sensory",1)],0,False),
 "sleep": ([("cond_asleep",1),("area_radius20",1),("no_save",1),("lim_hp_pool",1)],0,False),
 "speak-with-animals": ([("util_speak",1),("lim_dm",1),("lim_no_combat",1)],0,False),
 "thunderwave": ([("dmg",9),("rel_save_half",1),("area_cube15",1),("forced_move",1),("lim_loud",1)],0,False),
 "unseen-servant": ([("util_servant",1),("lim_fragile",1),("lim_no_combat",1)],0,False),
 "witch-bolt": ([("dmg",6.5),("rel_attack",1),("dmg_recurring",6.5),("lim_maintain_action",1),("lim_range_break",1)],0,False),
}



# Cantrip builds. Same format as B.
BC = {
 "acid-splash": ([("c_dmg",3.5),("lim_save_negates",1),("target_extra",1)],0,False),
 "chill-touch": ([("c_dmg",4.5),("rel_attack",1),("c_no_heal",1)],0,False),
 "dancing-lights": ([("c_lights4",1)],0,False),
 "druidcraft": ([("c_nature",1),("lim_cosmetic",1)],0,False),
 "eldritch-blast": ([("c_dmg",5.5),("rel_attack",1)],0,False),
 "fire-bolt": ([("c_dmg",5.5),("rel_attack",1),("util_ignite",1)],0,False),
 "guidance": ([("c_d4_check",1),("lim_willing",1)],0,False),
 "light": ([("c_light",1)],0,False),
 "mage-hand": ([("c_hand",1)],0,False),
 "mending": ([("c_mend",1)],0,False),
 "message": ([("c_message",1)],0,False),
 "minor-illusion": ([("c_illusion_min",1),("area_cube5",1),("lim_physical_reveal",1),("lim_sensory",1)],0,False),
 "poison-spray": ([("c_dmg",6.5),("lim_save_negates",1)],0,False),
 "prestidigitation": ([("c_trick",1),("lim_cosmetic",1),("lim_decay",1)],0,False),
 "produce-flame": ([("c_light",1),("c_dmg",4.5),("rel_attack",1),("lim_expend",1)],0,False),
 "ray-of-frost": ([("c_dmg",4.5),("rel_attack",1),("c_slow10",1)],0,False),
 "resistance": ([("c_d4_save",1),("lim_willing",1)],0,False),
 "sacred-flame": ([("c_dmg",4.5),("lim_save_negates",1),("c_ignore_cover",1)],0,False),
 "shillelagh": ([("c_weapon",1)],0,False),
 "shocking-grasp": ([("c_dmg",4.5),("rel_attack",1),("c_no_reactions",1)],0,False),
 "spare-the-dying": ([("c_stabilize",1)],0,False),
 "thaumaturgy": ([("c_wonder",1),("lim_cosmetic",1)],0,False),
 "true-strike": ([("c_adv_self",1)],0,False),
 "vicious-mockery": ([("c_dmg",2.5),("lim_save_negates",1),("c_disadv_next",1)],0,False),
}


# Level 2 builds.
B2 = {
 "acid-arrow": ([("dmg",10),("rel_attack",1),("dmg_recurring",5),("miss_half",1)],0,False),
 "aid": ([("temp_hp",5),("target_extra",2)],0,False),
 "alter-self": ([("util_alter_self",1)],0,False),
 "animal-messenger": ([("util_messenger",1),("lim_no_combat",1),("lim_type",1)],0,False),
 "arcane-lock": ([("util_lock",1),("persist",1)],25,True),
 "arcanists-magic-aura": ([("util_magic_aura",1),("lim_no_combat",1)],0,False),
 "augury": ([("util_augury",1),("lim_no_combat",1),("lim_dm",1)],25,False),
 "barkskin": ([("ac_bonus",3),("lim_willing",1)],0,False),
 "blindness-deafness": ([("cond_blinded",1),("lim_repeat_save",1)],0,False),
 "blur": ([("blur",1)],0,False),
 "calm-emotions": ([("util_calm",1),("area_radius20",1),("lim_willing",1)],0,False),
 "continual-flame": ([("util_flame",1),("persist",1),("lim_no_combat",1)],50,True),
 "crown-of-madness": ([("cond_crown",1),("lim_repeat_save",1),("lim_maintain_action",1),("lim_type",1)],0,False),
 "darkness": ([("util_darkness",1),("area_radius15",1)],0,False),
 "darkvision": ([("util_darkvision",1),("lim_willing",1)],0,False),
 "detect-thoughts": ([("util_thoughts",1),("lim_dm",1)],0,False),
 "enhance-ability": ([("enhance",1)],0,False),
 "enlarge-reduce": ([("resize",1)],0,False),
 "enthrall": ([("util_enthrall",1),("lim_dm",1)],0,False),
 "find-traps": ([("util_find_traps",1),("lim_no_combat",1)],0,False),
 "flame-blade": ([("dmg",10.5),("rel_attack",1),("dmg_recurring",10.5),("c_light",1)],0,False),
 "flaming-sphere": ([("dmg",7),("rel_save_half",1),("dmg_recurring",7),("area_cube5",1)],0,False),
 "gentle-repose": ([("util_repose",1),("lim_no_combat",1)],0,False),
 "gust-of-wind": ([("forced_move",1),("area_line60",1),("difficult_terrain",1),("util_wind",1)],0,False),
 "heat-metal": ([("dmg",9),("rel_auto",1),("dmg_recurring",9),("lim_maintain_action",1),("lim_escape_check",1)],0,False),
 "hold-person": ([("cond_paralyzed",1),("lim_repeat_save",1),("lim_type",1)],0,False),
 "invisibility": ([("invisible",1),("lim_ends_on_attack",1)],0,False),
 "knock": ([("util_knock",1),("lim_loud",1),("lim_no_combat",1)],0,False),
 "lesser-restoration": ([("util_cure",1)],0,False),
 "levitate": ([("util_levitate",1)],0,False),
 "locate-animals-or-plants": ([("util_locate_life",1),("lim_no_combat",1)],0,False),
 "locate-object": ([("util_locate",1),("lim_no_combat",1)],0,False),
 "magic-mouth": ([("util_mouth",1),("persist",1),("lim_no_combat",1)],10,True),
 "magic-weapon": ([("magic_weapon",1)],0,False),
 "mirror-image": ([("mirror",1)],0,False),
 "misty-step": ([("teleport",1)],0,False),
 "moonbeam": ([("dmg",11),("rel_save_half",1),("dmg_recurring",11),("area_radius5",1)],0,False),
 "pass-without-trace": ([("stealth_aura",1),("area_radius30",1)],0,False),
 "prayer-of-healing": ([("heal",12),("target_extra",5),("lim_exclude",1)],0,False),
 "protection-from-poison": ([("util_poison_prot",1)],0,False),
 "ray-of-enfeeblement": ([("cond_enfeeble",1),("rel_attack",1),("lim_repeat_save",1)],0,False),
 "rope-trick": ([("util_rope",1),("lim_no_combat",1)],0,False),
 "scorching-ray": ([("dmg",21),("rel_attack",1),("split_targets",1)],0,False),
 "see-invisibility": ([("util_see_invis",1)],0,False),
 "shatter": ([("dmg",13.5),("rel_save_half",1),("area_radius10",1),("lim_loud",1)],0,False),
 "silence": ([("util_silence",1),("area_radius20",1)],0,False),
 "spider-climb": ([("util_climb",1),("lim_willing",1)],0,False),
 "spike-growth": ([("zone_damage",5),("area_radius20",1),("difficult_terrain",1),("util_hidden",1)],0,False),
 "spiritual-weapon": ([("dmg",7.5),("rel_attack",1),("dmg_recurring",7.5)],0,False),
 "suggestion": ([("cond_suggestion",1),("lim_end_on_harm",1),("lim_harmless_only",1)],0,False),
 "warding-bond": ([("ward_bond",1),("lim_shared_damage",1),("lim_willing",1)],100,False),
 "web": ([("cond_restrained",1),("area_cube20",1),("difficult_terrain",1),("lim_escape_check",1),("lim_fragile",1)],0,False),
 "zone-of-truth": ([("util_truth",1),("area_radius15",1)],0,False),
}

# Upcasting. slug -> (item, increase per slot level). A step every two levels counts as half.
# Spells that scale in some other way (duration, radius, HP pools) are left out and pay a flat charge.
UPCAST = {
 "animal-friendship": ("target_extra", 1), "bane": ("target_extra", 1), "bless": ("target_extra", 1),
 "burning-hands": ("dmg", 3.5), "charm-person": ("target_extra", 1), "command": ("target_extra", 1),
 "cure-wounds": ("heal", 4.5), "false-life": ("temp_hp", 5), "guiding-bolt": ("dmg", 3.5),
 "healing-word": ("heal", 2.5), "hellish-rebuke": ("dmg", 5.5), "heroism": ("target_extra", 1),
 "inflict-wounds": ("dmg", 5.5), "longstrider": ("target_extra", 1), "magic-missile": ("dmg", 3.5),
 "thunderwave": ("dmg", 4.5), "witch-bolt": ("dmg", 6.5),
 "acid-arrow": ("dmg", 5), "aid": ("temp_hp", 5), "blindness-deafness": ("target_extra", 1),
 "enhance-ability": ("target_extra", 1), "flame-blade": ("dmg", 1.75), "flaming-sphere": ("dmg", 3.5),
 "heat-metal": ("dmg", 4.5), "hold-person": ("target_extra", 1), "invisibility": ("target_extra", 1),
 "moonbeam": ("dmg", 5.5), "prayer-of-healing": ("heal", 4.5), "scorching-ray": ("dmg", 7),
 "shatter": ("dmg", 4.5), "spiritual-weapon": ("dmg", 2.25),
}

# Spells whose damaging part reaches farther than the listed range (Produce Flame is Self, but hurls 30 ft).
PRICE_RANGE = {"produce-flame": "30 feet"}
